#!/bin/bash
set -euo pipefail
# Written by Anders L. Thorsen, March 2020

tensor_dir=/s4ever/anwG/NP/yvdwerf/data_Bergen/DWI/tensors

cd ${tensor_dir}

ls DWI_*_T0*_dtitk.nii.gz > T0_tensors.txt

sed -e "s/^DWI_//" -e "s/_T0_dtitk.nii.gz//" T0_tensors.txt > new_T0_tensors.txt

for subj in `cat new_T0_tensors.txt`; do

if [ -e "DWI_${subj}_T0_dtitk.nii.gz" ] && [ -e "DWI_${subj}_T2_dtitk.nii.gz" ]; then
		echo ${subj} >> subj_complete_data.txt
		mkdir tensor_${subj}
		mv DWI_${subj}_T0_dtitk.nii.gz DWI_${subj}_T2_dtitk.nii.gz tensor_${subj}
		printf "DWI_${subj}_T0_dtitk.nii.gz\nDWI_${subj}_T2_dtitk.nii.gz\n" > ./tensor_${subj}/${subj}.txt

	elif [ -e "DWI_${subj}_T0_dtitk.nii.gz" ] && [ ! -e "DWI_${subj}_T2_dtitk.nii.gz" ]; then
		mkdir tensor_${subj}
		mv DWI_${subj}_T0_dtitk.nii.gz tensor_${subj}
		echo ${subj} >> subj_T0_data.txt
fi

done

: << END



/s4ever/anwG/NP/yvdwerf/data_Bergen/DWI/tensors/tensor_00001


DWI_00001_T0_dtitk.nii.gz
printf "first\nsecond\n"

if [ ! -e "dtitk_files.txt" ]; then
	ls DWI_*_T*_dtitk.nii.gz > dtitk_files.txt
	for subj in `cat dtitk_files.txt`; do 
	TVResample -in ${subj} -align center -size 128 128 64 -vsize 1.5 1.75 2.25 
else
	echo "Tensor files may already have been transformed, please check that voxel size 1.5 1.75 2.25 is with the command 'VolumeInfo tensorfile.nii.gz'"

fi
END
